version: "3.7"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
